pluginManagement {
    repositories {
        maven { url = uri("$rootDir/local-maven") }
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.android.application") {
                useModule("com.android.tools.build:gradle:${requested.version}")
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = uri("$rootDir/local-maven") }
        google()
        mavenCentral()
    }
}

rootProject.name = "android_test"
include(":app")
